# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       blts-filesystem-perf

# >> macros
# << macros

Summary:    BLTS filesystem performance test suite
Version:    0.0.1
Release:    0
Group:      Development/Testing
License:    GPLv2
URL:        https://github.com/mer-qa/blts-filesystem-perf
Source0:    %{name}-%{version}.tar.gz
Source100:  blts-filesystem-perf.yaml
Requires:   iozone
Requires:   bonnie++

%description
This package contains filesystem performance tests


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
mkdir -p %{buildroot}/opt/tests/blts-filesystem-perf
install --mode=755 run-bonnie++.sh %{buildroot}/opt/tests/blts-filesystem-perf
install --mode=755 run-iozone.sh %{buildroot}/opt/tests/blts-filesystem-perf
install --mode=644 tests.xml %{buildroot}/opt/tests/blts-filesystem-perf
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
/opt/tests/blts-filesystem-perf/*
# >> files
# << files
